site_name: Edpzou
theme: material 
pages:
  - Home: index.md
  - Python: 
    - 'PYTHON之装饰器详解': 'python/python-decraoter.md'
  - Tools: 
    - 'Jupyterhub 部署教程': 'tools/jupyterhub-deploy.md'
    - 'Antlr4 安装教程': 'tools/antlr4-install.md'
  - 机器学习:
    - '数学篇--导数概念': 'machine/math/daoshu.md'
  - About: about.md